### ISSUE TITLE
beacons

### ISSUE THREAD

**Issue by ccoulton** [ccoulton/android-sdk#1]
Beacons causing a crash when bound importing to another project

**Comment by ccoulton** [comment]
QwasiLocationManager

``` java
   @Override                                                                                                          
   public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {  //issue #1                       
       for (Beacon beacon : beacons) {                                                                                
           if (beacon.getServiceUuid() == 0xfeaa && beacon.getBeaconTypeCode() == 0x00) {                             
               //Eddystone-UID frame                                                                                  
               Identifier namespaceId = beacon.getId1();                                                              
               Identifier instanceId = beacon.getId2();                                                               
               Log.d("QwasiRanging", "Beacon Sighted with namespace id: " + namespaceId                               
                       + "and instance " + instanceId + " approx " + beacon.getDistance() + "meters away.");          
               QwasiLocation temp = new QwasiLocation(mLastLocation);                                                 
               temp.state = QwasiLocationState.QwasiLocationStateInside;                                              
               temp.type = QwasiLocationType.QwasiLocationTypeBeacon;                                                 
               Witness.notify(temp);                                                                                  
           }                                                                                                          
       }                                                                                                              
   }                                                                                                                  

   public Context getApplicationContext(){       //#issue 1                                                           
       return sharedApplication.getApplicationContext();                                                              
   }                                                                                                                  
```

QwasiAppManager

``` java
@Override
    public void onActivityResumed(Activity activity){
        data = new HashMap<>();
        event = "com.qwasi.event.application.state";
        data.put("", "");
        if (postEvent.getState() == Thread.State.TERMINATED)
            postEvent.start();
        ++resumed;
        if (!sharedApplication.mlocationManager.mmanager.isConnected())
            sharedApplication.mlocationManager.mmanager.connect();
        sharedApplication.mlocationManager.beaconManager = BeaconManager.getInstanceForApplication(sharedApplication.getContext());
        sharedApplication.mlocationManager.beaconManager.getBeaconParsers().add(new BeaconParser()
                .setBeaconLayout("s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19"));
        //sharedApplication.mlocationManager.beaconManager.bind(sharedApplication.mlocationManager);  //#issue 1
    }

    @Override
    public void onActivityPaused(Activity activity){
        Log.d("QwasiDebug", "ActivityPaused");
        ++paused;
        sharedApplication.mlocationManager.mmanager.disconnect();
        android.util.Log.w("test", "application is in foreground: " + (resumed > paused));
        //sharedApplication.mlocationManager.beaconManager.unbind(sharedApplication.mlocationManager); //issue #1
    }
```

**Comment by davidgyoung** [comment]
Can you please tell me on what line you see the crash, and what the exception is?

**Comment by ccoulton** [comment]
it's a null pointer execption on the beaconmanger.bind(BeaconConsumer) line 284, and then that goes to Context Wrapper.bindService, it might be I don't have beacons declared in the manifest, but i've tried adding the library to the gradle

 java.lang.RuntimeException: Unable to resume activity {com.qwasi.qwasidemo/com.qwasi.qwasidemo.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2826)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2859)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2274)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5102)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.content.ContextWrapper.bindService(ContextWrapper.java:517)
            at org.altbeacon.beacon.BeaconManager.bind(BeaconManager.java:284)
            at com.qwasi.sdk.QwasiAppManager.onActivityResumed(QwasiAppManager.java:63)
            at android.app.Application.dispatchActivityResumed(Application.java:208)
            at android.app.Activity.onResume(Activity.java:1105)
            at com.qwasi.qwasidemo.MainActivity.onResume(MainActivity.java:115)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1215)
            at android.app.Activity.performResume(Activity.java:5327)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2811)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2859)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2274)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5102)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ccoulton** [comment]
it's at the line consumer.bindService(intent, this.beaconServiceConnection, 1); before the consumer count log call

**Comment by davidgyoung** [comment]
Is it possible that `sharedApplication.getContext()` is null in this line:

```
sharedApplication.mlocationManager.beaconManager = BeaconManager.getInstanceForApplication(sharedApplication.getContext());
```

You could check that by logging the value of `sharedApplication.getContext()` near the line above.

**Comment by ccoulton** [comment]
that's talking to my main library object asking for the host application context, put it outside as a temp varirable and it has all the correct context for the .MainActivity of the application, or is that a different context I'm spost to use

Should i need to connect the service for the beacons back to locationmanager alal i had to for geofences? or is there a need to put the merge command into the manifest?

**Comment by davidgyoung** [comment]
I think you will have to add the AndroidManifest entries manually.  Manifest merging works for applications only not for library projects.  

I would copy everything here into your project manifest:

https://github.com/AltBeacon/android-beacon-library/blob/master/src/main/AndroidManifest.xml

And see if that makes a difference

**Comment by ccoulton** [comment]
crashes in the same spot in the sample app that is using the 2 libraries... is there anyway to set it up so that my libraries' gradle dependancies and manifest are pulled from the maven import? is that included in your library?

**Comment by davidgyoung** [comment]
I don't think gradle supports merging multiple library dependencies
together automatically.  When I need to do this, I script it to crack open
the .aar file from the Android Beacon Library and include its jar files in
your project manually and include the manifest entries.

**Comment by ccoulton** [comment]
ok it's the mBase of the contextWrapper that is null, 

``` java
 @Override
    public boolean bindService(Intent service, ServiceConnection conn, conn:BeaconManager, service"intent{cmp=com.qwasi.qwasidemo/org.altbeacon.beacon.service.BeaconService flags: 1
            int flags) {
        return mBase.bindService(service, conn, flags); mBase is null here
    }
```

**Comment by ccoulton** [comment]
is it because my consumer isn't an activity?

**Comment by ccoulton** [comment]
ok so I put the consumer on the mainActivity and it works.  Is there anyway to keep that internally to decrease setup for the user?

**Comment by davidgyoung** [comment]
It is OK to have your consumer not be an activity, but you must chain all the methods in the interface to equivalent methods on a valid Context. Make sense?

For the BeaconParser expression,  the matching pattern (the part with m) should only cover bytes 2 and 3.  And you should be aware that publishing this in an open source project might catch you heat from the sponsor of the proprietary beacon format. (Maybe you won't, but it has happened.)

**Comment by ccoulton** [comment]
Regarding the iBeaconparser, your probly right i'll be taking that out c.y.b. and all that.  I get that it needs to be chained down but I still don't get how to get context to a intentservice even after calling the super constructor so I'll play around with maybe subclassing again to see if that can work but I definatly got it to work by passing it the main activity cast as a beaconconsumer.  That only works because in the test application I can know/assume that it is a beaconconsumer.

**Comment by davidgyoung** [comment]
An IntentService instance is a valid Context.  You can make it the BeaconConsumer, or chain methods to its instance.

**Comment by ccoulton** [comment]
Ok well thanks very much for your help, I can't figure out what I'm missing to make it work off of the IntentService why it's not getting its mBase set But I'm going to close this, I got it to work in one context.  I'll play around till I can get the internal Intent service to work
